CREATE TABLE User(
  UserID INT NOT NULL AUTO_INCREMENT,
  UserName VARCHAR(20) NOT NULL,
  PRIMARY KEY (UserID)
);
CREATE TABLE UserData(
  UserID INT NOT NULL,
  Age INT,
  Sex VARCHAR(1),
  FOREIGN KEY (UserID) REFERENCES User(UserID)
);
CREATE TABLE Sublet(
  SubletID INT NOT NULL AUTO_INCREMENT,
  UserID INT NOT NULL,
  Address VARCHAR(50),
  Description VARCHAR(120),
  PRIMARY KEY (SubletID),
  FOREIGN KEY (UserID) REFERENCES User(UserID)
);
CREATE TABLE SubletData(
  SubletID INT NOT NULL,
  UserID INT NOT NULL,
  Description VARCHAR(1200),
  NumOfRoommates INT,
  Furnished BOOLEAN,
  FOREIGN KEY (SubletID) REFERENCES Sublet(SubletID),
  FOREIGN KEY (UserID) REFERENCES User(UserID)
);
CREATE TABLE MessageRooms(
  RoomID INT NOT NULL AUTO_INCREMENT,
  SubletID INT NOT NULL AUTO_INCREMENT,
  User1 INT NOT NULL,
  User2 INT NOT NULL,
  PRIMARY KEY (RoomID),
  FOREIGN KEY (SubletID) REFERENCES Sublet(SubletID),
  FOREIGN KEY (User1) REFERENCES User(UserID),
  FOREIGN KEY (User2) REFERENCES User(UserID)
);
CREATE TABLE Messages(
  MessageID INT NOT NULL AUTO_INCREMENT,
  UserID INT NOT NULL,
  RoomID INT,
  Message VARCHAR(500),
  PRIMARY KEY (MessageID),
  FOREIGN KEY (UserID) REFERENCES User(UserID)
);
